# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create([{ email: 'guest@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Guest',
              surname: 'Bulma',
              gender:'female',
              date_birth: '01/01/1990',
              phone: '',
              adress: '1 rue de paris',
              zip_code: '75010',
              town: 'paris',
              country:'France',
              role_guest:'true',
              role_host: '',
              role_both:'',
              description:'',
              langage:'french',
              photos:'http://www.dragon-ball-z.org/images/personnages/avatars_bulma_2.jpg',
  }])
User.create([{ email: 'host@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Host',
              surname:'Hercule',
              gender:'male',
              date_birth: '31/08/1982',
              phone: '',
              adress: '28 avenue des champs elysées',
              zip_code: '75008',
              town: 'paris',
              country:'France',
              role_guest:'',
              role_host: 'true',
              role_both:'',
              description:'',
              langage:'french',
              photos:'http://www.wtfgamersonly.com/wp-content/uploads/2015/07/Mr-Satan.jpg',
  }])
User.create([{ email: 'both@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Both',
              surname:'Tortue géniale',
              gender:'male',
              date_birth: '10/10/1950',
              phone: '',
              adress: '30 reu de la place',
              zip_code: '78000',
              town: 'versailles',
              country:'France',
              role_guest:'',
              role_host: '',
              role_both:'true',
              description:'',
              langage:'french',
              photos:'http://dball.free.fr/dball/perso/perso_principaux/tortue/tortue4.gif',
  }])
Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 4,
                city: 'Paris',
                title:'Appartement in RIO',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 200.00,
                adress: 'Rue de Paris',
                zip_code: 75015,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.bright-immobilier.com/wp-content/uploads/appartement-paris_8-rue-jean-mermoz_01-950x534.jpg', 

  }])

Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 4,
                city: 'Paris',
                title: 'Appartement in Paris',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 200.00,
                adress: 'Rue de Paris',
                zip_code: 75015,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.egr-renovation.com/images/post-images/renovation-appartement-paris-15.jpg', 

  }])
Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 4,
                city: 'Versailles',
                title: 'Appartement in Paris',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 200.00,
                adress: 'Rue de Paris',
                zip_code: 78000,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.appartement-paris-vacances.fr/photos/9709.jpg', 

  }])
Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 4,
                city: 'Dreux',
                title: 'Appartement in Paris',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 200.00,
                adress: 'Rue de Paris',
                zip_code: 28100,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://referentiel.nouvelobs.com/file/5677948.jpg', 

  }])