# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create([{ email: 'guest@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Guest',
              surname: 'Bulma',
              gender:'female',
              date_birth: '01/01/1990',
              phone: '',
              adress: '1 rue de paris',
              zip_code: '75010',
              town: 'paris',
              country:'France',
              role_guest:'true',
              role_host: '',
              role_both:'',
              description:'',
              langage:'french',
              photos:'http://www.dragon-ball-z.org/images/personnages/avatars_bulma_2.jpg',
  }])
User.create([{ email: 'host@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Host',
              surname:'Hercule',
              gender:'male',
              date_birth: '31/08/1982',
              phone: '',
              adress: '28 avenue des champs elysées',
              zip_code: '75008',
              town: 'paris',
              country:'France',
              role_guest:'',
              role_host: 'true',
              role_both:'',
              description:'',
              langage:'french',
              photos:'http://www.wtfgamersonly.com/wp-content/uploads/2015/07/Mr-Satan.jpg',
  }])
User.create([{ email: 'both@toto.com',
              password: 'jecode4laloupe',
              password_confirmation: 'jecode4laloupe',
              name: 'Both',
              surname:'Tortue géniale',
              gender:'male',
              date_birth: '10/10/1950',
              phone: '',
              adress: '30 reu de la place',
              zip_code: '78000',
              town: 'versailles',
              country:'France',
              role_guest:'',
              role_host: '',
              role_both:'true',
              description:'',
              langage:'french',
              photos:'http://dball.free.fr/dball/perso/perso_principaux/tortue/tortue4.gif',
  }])
Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 12,
                city: 'Paris',
                title:'Appartement in Paris',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 208.00,
                adress: 'Rue lecourbe',
                zip_code: 75015,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.bright-immobilier.com/wp-content/uploads/appartement-paris_8-rue-jean-mermoz_01-950x534.jpg',
                images1:"http://jinxpro2.xyz/wp-content/uploads/2015/09/Amazing-simple-bedrooms-decorations-ideas.jpg",
                images2:"http://modernekuche.xyz/wp-content/uploads/2015/10/Amazing-simple-bedroom-interior-design.jpg",
                images3:"http://www.designhow.co/wp-content/uploads/2015/03/uncategorized-stunning-modern-bedroom-combined-with-simple-interior-design-simple-bedroom-interior-design.jpg",
                images4:"http://yeeee.co/wp-content/uploads/2015/10/simple-bedroom-fresh-with-photos-of-simple-bedroom-collection-new-in-gallery.jpg",
                user_id: 1,
  }])

Appart.create([{ room_type: true,
                property_type: 'Loft',
                accommodates: 8,
                city: 'Paris',
                title: 'Loft in Paris',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 202.00,
                adress: 'Avenue des Champs Elysées',
                zip_code: 75008,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.egr-renovation.com/images/post-images/renovation-appartement-paris-15.jpg',
                images1:"http://parisinpink.com/wp-content/uploads/2015/10/bedroom-design-throughout-14-master-bedroom-design-ideas-tips-for-finding-some-magnificent.jpg",
                images2:"http://img01.deviantart.net/bfea/i/2011/118/5/f/interior_master_bedroom_by_arclabelle-d3f2jtm.jpg",
                images3:"http://addodecor.com/wp-content/uploads/2012/12/Calming-Master-Bedroom-Interior-Design-with-Large-Mirror.jpg",
                images4:"http://labs2.kentooz.com/kodok/wp-content/uploads/2013/04/bedroom-design-190.jpg",
                user_id: 2,
  }])
Appart.create([{ room_type: true,
                property_type: 'Appartement',
                accommodates: 4,
                city: 'Versailles',
                title: 'Appartement Versailles',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 203.00,
                adress: 'Rue du refuge',
                zip_code: 78000,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://www.appartement-paris-vacances.fr/photos/9709.jpg',
                images1:"",
                images2:"",
                images3:"",
                images4:"",
                user_id: 1,
  }])
Appart.create([{ room_type: true,
                property_type: 'Maison',
                accommodates: 2,
                city: 'Dreux',
                title: 'Maison Dreux',
                bedroom_nb: 2,
                beds_nb: 2,
                price: 201.00,
                adress: 'Boulevard Dubois',
                zip_code: 28100,
                country: 'France',
                amenities: "PQ / Serviettes / TV / Internet",
                images:'http://referentiel.nouvelobs.com/file/5677948.jpg',
                images1:"",
                images2:"",
                images3:"",
                images4:"",
                user_id: 1,
  }])
